include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false  # Allowed for PoC debugging
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
